---
abstract: 'remove leading and/or trailing whitespace from strings'
author:
  - 'Matt Lawrence <mattlaw@cpan.org>'
  - 'Ryan Thompson <rjt@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec::Functions: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Text-Trim
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006'
resources:
  X_metaspec:
    version: 2
  bugtracker: https://github.com/rjt-pl/Text-Trim/issues
  repository: https://github.com/rjt-pl/Text-Trim.git
version: '1.04'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
